### ISSUE TITLE
Looking forward to an additional download channel

### ISSUE THREAD

**Issue by o0Helloworld0o** [octree-nn/ognn-pytorch#1]
Thank you for continuously updating and maintaining the code for your great work~
The training weights you provided are stored on OneDrive, which is not very convenient for me to access. Can you provide an alternative download channel (such as Google Drive)? 
Thanks a lot.

**Comment by wang-ps** [comment]
Thanks for your suggestions. It is hard for me to access Google Drive since I am located in China.
