### ISSUE TITLE
Regarding the Implementation of GraphConv and the Setting of n_node_type

### ISSUE THREAD

**Issue by o0Helloworld0o** [octree-nn/ognn-pytorch#4]
Hi,  I have been trying your great job lately, thank you for rewriting and sharing this pure PyTorch code.

After many attempts and reading the source code, I have some doubts about the implementation of GraphConv.

(1) I saw that feature `x` was concatenated with a `one_hot` vector, but I couldn't find the relative direction of $\Delta p_{ij}$ mentioned in the paper in the code.

(2) Since one-hot encoding is used, I think we should add such a check, `assert graph.node_type.max() + 1 == self.n_node_type`,  to ensure the rationality of one-hot encoding.

However, in the DFaust experiment, this assertion did not hold true. I think `self.n_node_type` should not be set to `7`, it should be set to `6`, corresponding to depth=3~8, a total of 6 situations.

Anyway, the above is my analysis. After modifying the code `self.n_node_type = 7 -> 6` and running DFaust experiment again, the experimental results still look good.

So I'm here to ask for your opinion, thank you!

**Comment by wang-ps** [comment]
![image](https://github.com/user-attachments/assets/fd6af3e7-838f-4c11-bf58-beb7d73165d5)

\delta p_ij  is mapped to discrete labels and then is used as one-hot vectors

**Comment by o0Helloworld0o** [comment]
Thank you for your quick reply. How about the setting of n_node_type in your opinion?

**Comment by wang-ps** [comment]
The code  can run  as long as  `n_node_type` is larger than the actual node type number
